//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebka3KYRSKrasnov.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Railing
    {
        public int ID_RH { get; set; }
        public int ID_Railing { get; set; }
        public int ID_Home { get; set; }
    
        public virtual Home Home { get; set; }
        public virtual Railing_For_Home Railing_For_Home { get; set; }
    }
}
