//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebka3KYRSKrasnov.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Cokol
    {
        public int ID_HC { get; set; }
        public int ID_Basement { get; set; }
        public int ID_Home { get; set; }
    
        public virtual Home Home { get; set; }
        public virtual House_Basement_Cokol_ House_Basement_Cokol_ { get; set; }
    }
}
