//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebka3KYRSKrasnov.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Door
    {
        public int ID_HD { get; set; }
        public int ID_Door { get; set; }
        public int ID_Home { get; set; }
    
        public virtual Door_For_House Door_For_House { get; set; }
        public virtual Home Home { get; set; }
    }
}
