//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebka3KYRSKrasnov.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseHomeEntities : DbContext
    {
        public DataBaseHomeEntities()
            : base("name=DataBaseHomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Balki_House> Balki_House { get; set; }
        public virtual DbSet<Door_For_House> Door_For_House { get; set; }
        public virtual DbSet<Drain_For_Home> Drain_For_Home { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<Home_Balki> Home_Balki { get; set; }
        public virtual DbSet<Home_Cokol> Home_Cokol { get; set; }
        public virtual DbSet<Home_Door> Home_Door { get; set; }
        public virtual DbSet<Home_Drain> Home_Drain { get; set; }
        public virtual DbSet<Home_Fasad> Home_Fasad { get; set; }
        public virtual DbSet<Home_Pavers> Home_Pavers { get; set; }
        public virtual DbSet<Home_Plaster> Home_Plaster { get; set; }
        public virtual DbSet<Home_Railing> Home_Railing { get; set; }
        public virtual DbSet<Home_Roof> Home_Roof { get; set; }
        public virtual DbSet<Home_Solution> Home_Solution { get; set; }
        public virtual DbSet<Home_Steps> Home_Steps { get; set; }
        public virtual DbSet<Home_Terrace> Home_Terrace { get; set; }
        public virtual DbSet<Home_Window> Home_Window { get; set; }
        public virtual DbSet<House_Basement_Cokol_> House_Basement_Cokol_ { get; set; }
        public virtual DbSet<House_Facade> House_Facade { get; set; }
        public virtual DbSet<House_Steps> House_Steps { get; set; }
        public virtual DbSet<House_Windows> House_Windows { get; set; }
        public virtual DbSet<Pavers_House> Pavers_House { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Plaster_for_the_house> Plaster_for_the_house { get; set; }
        public virtual DbSet<Railing_For_Home> Railing_For_Home { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Roof_of_the_house> Roof_of_the_house { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Terrace_Home> Terrace_Home { get; set; }
        public virtual DbSet<Turnkey_solution_for_home> Turnkey_solution_for_home { get; set; }
    }
}
