//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebka3KYRSKrasnov.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ID_Person { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Auth Auth { get; set; }
    }
}
